/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CommunityPost {
  'id' : bigint,
  'city' : string,
  'name' : string,
  'message' : string,
  'timestamp' : bigint,
  'college' : string,
}
export interface FoodSpot {
  'id' : bigint,
  'spotType' : string,
  'name' : string,
  'description' : string,
  'priceRange' : string,
  'location' : string,
}
export interface LanguagePhrase {
  'id' : bigint,
  'meaning' : string,
  'language' : string,
  'phrase' : string,
}
export interface Listing {
  'id' : bigint,
  'title' : string,
  'postedBy' : string,
  'contact' : string,
  'rent' : bigint,
  'amenities' : string,
  'timestamp' : bigint,
  'location' : string,
}
export interface TransportTip {
  'id' : bigint,
  'title' : string,
  'mode' : string,
  'description' : string,
}
export interface _SERVICE {
  'addCommunityPost' : ActorMethod<[string, string, string, string], bigint>,
  'addListing' : ActorMethod<
    [string, string, bigint, string, string, string],
    bigint
  >,
  'getAllCommunityPosts' : ActorMethod<[], Array<CommunityPost>>,
  'getAllFoodSpots' : ActorMethod<[], Array<FoodSpot>>,
  'getAllLanguagePhrases' : ActorMethod<[], Array<LanguagePhrase>>,
  'getAllListings' : ActorMethod<[], Array<Listing>>,
  'getAllListingsSortedByRent' : ActorMethod<[], Array<Listing>>,
  'getAllTransportTips' : ActorMethod<[], Array<TransportTip>>,
  'getCommunityPostsByCollege' : ActorMethod<[string], Array<CommunityPost>>,
  'getDistinctColleges' : ActorMethod<[], Array<string>>,
  'getFoodSpotsByType' : ActorMethod<[string], Array<FoodSpot>>,
  'getLanguagePhrasesByLanguage' : ActorMethod<[string], Array<LanguagePhrase>>,
  'getListingById' : ActorMethod<[bigint], Listing>,
  'getListingsByLocation' : ActorMethod<[string], Array<Listing>>,
  'getTransportTipsByMode' : ActorMethod<[string], Array<TransportTip>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];