/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CommunityPost = IDL.Record({
  'id' : IDL.Nat,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'college' : IDL.Text,
});
export const FoodSpot = IDL.Record({
  'id' : IDL.Nat,
  'spotType' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'priceRange' : IDL.Text,
  'location' : IDL.Text,
});
export const LanguagePhrase = IDL.Record({
  'id' : IDL.Nat,
  'meaning' : IDL.Text,
  'language' : IDL.Text,
  'phrase' : IDL.Text,
});
export const Listing = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'postedBy' : IDL.Text,
  'contact' : IDL.Text,
  'rent' : IDL.Nat,
  'amenities' : IDL.Text,
  'timestamp' : IDL.Int,
  'location' : IDL.Text,
});
export const TransportTip = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'mode' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'addCommunityPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAllCommunityPosts' : IDL.Func([], [IDL.Vec(CommunityPost)], ['query']),
  'getAllFoodSpots' : IDL.Func([], [IDL.Vec(FoodSpot)], ['query']),
  'getAllLanguagePhrases' : IDL.Func([], [IDL.Vec(LanguagePhrase)], ['query']),
  'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getAllListingsSortedByRent' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getAllTransportTips' : IDL.Func([], [IDL.Vec(TransportTip)], ['query']),
  'getCommunityPostsByCollege' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CommunityPost)],
      ['query'],
    ),
  'getDistinctColleges' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getFoodSpotsByType' : IDL.Func([IDL.Text], [IDL.Vec(FoodSpot)], ['query']),
  'getLanguagePhrasesByLanguage' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LanguagePhrase)],
      ['query'],
    ),
  'getListingById' : IDL.Func([IDL.Nat], [Listing], ['query']),
  'getListingsByLocation' : IDL.Func([IDL.Text], [IDL.Vec(Listing)], ['query']),
  'getTransportTipsByMode' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TransportTip)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CommunityPost = IDL.Record({
    'id' : IDL.Nat,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'college' : IDL.Text,
  });
  const FoodSpot = IDL.Record({
    'id' : IDL.Nat,
    'spotType' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'priceRange' : IDL.Text,
    'location' : IDL.Text,
  });
  const LanguagePhrase = IDL.Record({
    'id' : IDL.Nat,
    'meaning' : IDL.Text,
    'language' : IDL.Text,
    'phrase' : IDL.Text,
  });
  const Listing = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'postedBy' : IDL.Text,
    'contact' : IDL.Text,
    'rent' : IDL.Nat,
    'amenities' : IDL.Text,
    'timestamp' : IDL.Int,
    'location' : IDL.Text,
  });
  const TransportTip = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'mode' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'addCommunityPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllCommunityPosts' : IDL.Func([], [IDL.Vec(CommunityPost)], ['query']),
    'getAllFoodSpots' : IDL.Func([], [IDL.Vec(FoodSpot)], ['query']),
    'getAllLanguagePhrases' : IDL.Func(
        [],
        [IDL.Vec(LanguagePhrase)],
        ['query'],
      ),
    'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getAllListingsSortedByRent' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getAllTransportTips' : IDL.Func([], [IDL.Vec(TransportTip)], ['query']),
    'getCommunityPostsByCollege' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CommunityPost)],
        ['query'],
      ),
    'getDistinctColleges' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getFoodSpotsByType' : IDL.Func([IDL.Text], [IDL.Vec(FoodSpot)], ['query']),
    'getLanguagePhrasesByLanguage' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LanguagePhrase)],
        ['query'],
      ),
    'getListingById' : IDL.Func([IDL.Nat], [Listing], ['query']),
    'getListingsByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getTransportTipsByMode' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TransportTip)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };